### ISSUE TITLE
Create `using_positron()`

### ISSUE THREAD

**Issue by briandconnelly** [briandconnelly/ami#28]
Positron seems to set both `POSITRON` and `POSITRON_VERSION`. I haven't found documentation for these, though.

`POSITRON_MODE` will also return "server" or "desktop".

**Comment by lattaai10** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the rstudio.R file to include checks for POSITRON and POSITRON_VERSION environment variables, and updated the mode detection to use POSITRON_MODE when available. Also added a new function `using_positron()` to check if code is running in Positron.

You can review changes in this commit: https://github.com/lattaai10/briandconnelly-ami-28/commit/0d77f0e99e3da90063316a2f35f636f1a388e7ae.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
